export const projects = [
    {
        id: 0,
        title: 'Mentup.Ru',
        description: "MentUp предоставляет возможность купить аккаунт стим и других игровых услуг в магазине игровых товаров.",
        category: "website",
        images: [
            "https://i.imgur.com/wrc3Cv5.png",
            "https://i.imgur.com/pArYDlo.png",
            "https://i.imgur.com/VsN8pGk.png",
            "https://i.imgur.com/gPvmwHb.png",
            "https://i.imgur.com/LFZHd2p.png"
        ],
        link: "https://mentup.ru/?utm_source=menshikov.agency",
        duration: "5-6 месяцев",
        layout: false,
    },
    {
        id: 123,
        title: 'News.Mentup.Ru',
        description: "Актуальные новости киберспорта, турниров, аналитика игр и события игровой индустрии",
        category: "website",
        images: [
            "https://i.imgur.com/s6pXTdr.png",
            "https://i.imgur.com/w3EgM4Q.png",
            "https://i.imgur.com/T21QPgq.png",
            "https://i.imgur.com/7xiPprs.png",
            "https://i.imgur.com/7hsq5zA.png"
        ],
        link: "https://news.mentup.ru/?utm_source=menshikov.agency",
        duration: "1 месяц",
        layout: false,
    },
    {
        id: 12123213,
        title: 'Twizz-Project.Ru',
        description: "Разработка ПО для киберспортивных команд + интеграция с EmailJS и Google Analytics 4",
        category: "website",
        images: [
            "https://i.imgur.com/RuxaO7N.png",
            "https://i.imgur.com/AmwWQz1.png",
            "https://i.imgur.com/nLJSc9y.png",
            "https://i.imgur.com/yWKDqIz.png",
            "https://i.imgur.com/ZaI9L0e.png",
            "https://i.imgur.com/Ob7ER6N.png",
            "https://i.imgur.com/NvDaEat.png",
            "https://i.imgur.com/2dt7uvp.png"
        ],
        link: "https://twizz-project.ru",
        duration: "1 день",
        layout: false,
    },
    {
        id: 121213,
        title: 'Дизайн сайта Fastbut365.By',
        description: "Сайт для заказа бытовой химии в Беларусь и Россию",
        category: "design",
        images: [
            "https://i.imgur.com/oyH856H.png",
            "https://i.imgur.com/48Qm2Ka.png",
            "https://i.imgur.com/N20TKR8.png",
            "https://i.imgur.com/ds0ZOwg.png",
            "https://i.imgur.com/0D9OZKR.png"
        ],
        link: "https://fastbuy365.by",
        duration: "10 дней",
        layout: false,
    },
    {
        id: 228,
        title: 'Hotel-Ring.Ru',
        description: "Сайт для бронирования отеля в Волгограде",
        category: "website",
        images: [
            "https://i.imgur.com/GOODpLZ.png",
            "https://i.imgur.com/7Tmim9M.png",
            "https://i.imgur.com/Aqb4CIT.png",
            "https://i.imgur.com/9KlXiqM.png",
            "https://i.imgur.com/YKmPxSc.png",
            "https://i.imgur.com/FZvqzrz.png"
        ],
        link: "https://hotel-ring.ru",
        duration: "8 дней",
        layout: false,
    },
    {
        id: 1,
        title: 'Telegram Mini App "PROPAGANDA AGENCY"',
        description: "Мини-приложение для медиа-агентства",
        category: "telegram",
        images: [
            "https://i.imgur.com/eAxFqoJ.png",
            "https://i.imgur.com/7UBVfn0.png",
            "https://i.imgur.com/KuRfw8f.png",
            "https://i.imgur.com/8MxHvBD.png",
            "https://i.imgur.com/S1fR7wO.png",
            "https://i.imgur.com/nILPThK.png",
            "https://i.imgur.com/pTLU5Yt.png",
            "https://i.imgur.com/VoXe00i.png",
            "https://i.imgur.com/DLiMJFR.png",
            "https://i.imgur.com/tkxy3we.png",
            "https://i.imgur.com/OSeFrEc.png",
            "https://i.imgur.com/u1frdeI.png",
            "https://i.imgur.com/yQhzByv.png",
            "https://i.imgur.com/qC5rUIB.png"
        ],
        link: "https://t.me/propagan_agency_bot/AGENCY",
        duration: "< 1 дня",
        layout: false,
    },
    {
        id: 2,
        title: 'Telegram Mini App "СИСТЕМА: продай на миллион за вечер" ',
        description: "Мини-приложение с интерактивным опросом и продажей инфопродукта",
        category: "telegram",
        images: [
            "https://i.imgur.com/uaQmJlz.png",
            "https://i.imgur.com/j0aXzMp.png",
            "https://i.imgur.com/4h8PW72.png",
            "https://i.imgur.com/O5h6by7.png",
            "https://i.imgur.com/AQewDy9.png",
            "https://i.imgur.com/wbMwrhy.png"
        ],
        link: "https://t.me/SISTEMAzh_bot/system",
        duration: "2 дня",
        layout: false,
    },
    {
        id: 3,
        title: 'Telegram Бот "Ethos Select"',
        description: "Бот для онлайн-магазина: заказы, заявки, админка",
        category: "bot",
        images: [
            "https://i.imgur.com/ATegrE3.png",
            "https://i.imgur.com/zzNQtsN.png",
            "https://i.imgur.com/q4zozwr.png",
            "https://i.imgur.com/hAGSA2x.png",
            "https://i.imgur.com/oUs0m3o.png",
            "https://i.imgur.com/w8NNb8J.png",
            "https://i.imgur.com/tqSRLs2.png"
        ],
        link: "https://t.me/ethos_select_bot",
        duration: "2 дня",
        layout: false,
    },
    {
        id: 4,
        title: 'Сайт "Гимназия ЛИДЕР"',
        description: "Современный сайт для современной школы",
        category: "website",
        images: [
            "https://i.imgur.com/vdwGuUs.png",
            "https://i.imgur.com/vaNlVfH.png",
            "https://i.imgur.com/l7OydoS.png",
            "https://i.imgur.com/d6ruShq.png",
            "https://i.imgur.com/fMsrzmN.png",
            "https://i.imgur.com/a14zmpu.png",
            "https://i.imgur.com/4SNYszl.png",
            "https://i.imgur.com/nFptiX2.png",
        ],
        link: "https://lider-gym.vercel.app",
        duration: "1 день",
        layout: false,
    },
    {
        id: 5,
        title: 'Telegram Mini App "Premium Brand"',
        description: "Мини-приложение для онлайн-магазина: дизайн, каталог товаров, интеграция с Google Excel",
        category: "telegram",
        images: [
            "https://i.imgur.com/hc4DQud.png",
            "https://i.imgur.com/gDvI41U.png",
            "https://i.imgur.com/xGCmrOJ.png",
            "https://i.imgur.com/xbKF336.png",
            "https://i.imgur.com/n8vA8KV.png"
        ],
        link: "https://t.me/premiumbrand_shop_bot/app",
        duration: "1 день",
        layout: false,
    },
    {
        id: 6,
        title: 'Telegram Mini App "Получить разбор на эфире"',
        description: "Мини-приложение для оставление заявки для разбора на эфире + интеграция с Google Excel",
        category: "telegram",
        images: [
            "https://i.imgur.com/1MhVtCm.png",
            "https://i.imgur.com/fm2o8ds.png",
            "https://i.imgur.com/5S6SsHk.png",
            "https://i.imgur.com/kgZAn92.png",
            "https://i.imgur.com/AncEYaG.png",
            "https://i.imgur.com/L3XagRi.png"
        ],
        link: "https://t.me/tigran_says_bot/app",
        duration: "< 1 день",
        layout: false,
    },
    {
        id: 61234,
        title: 'Дизайн сайта Stomart.Ru',
        description: "Сайт для продажи медицинского оборудования для стоматологов с доставкой по всей России",
        category: "design",
        images: [
            "https://i.imgur.com/L4V3Ckb.png",
            "https://i.imgur.com/PWdMv9P.png",
            "https://i.imgur.com/NKZbZpV.png",
            "https://i.imgur.com/sHeqs3L.png",
            "https://i.imgur.com/nhXK5CN.png"
        ],
        link: "https://www.stomart.ru",
        duration: "2 недели",
        layout: false,
    },
    {
        id: 7,
        title: 'Telegram Mini App "Получить разбор на эфире" 2',
        description: "Мини-приложение для оставление заявки для разбора на эфире + интеграция с Google Excel",
        category: "telegram",
        images: [
            "https://i.imgur.com/2YGeUEx.png",
            "https://i.imgur.com/bV62vjO.png",
            "https://i.imgur.com/1c5edn9.png",
            "https://i.imgur.com/nyTQvX0.png",
            "https://i.imgur.com/GPqcLST.png",
            "https://i.imgur.com/yoTOcM3.png"
        ],
        link: "https://t.me/villagi0_bot/bot",
        duration: "< 1 день",
        layout: false,
    },
    {
        id: 81234,
        title: 'Дизайн сайта Mentup.Ru',
        description: "MentUp предоставляет возможность купить аккаунт стим и других игровых услуг в магазине игровых товаров.",
        category: "design",
        images: [
            "https://i.imgur.com/wrc3Cv5.png",
            "https://i.imgur.com/pArYDlo.png",
            "https://i.imgur.com/VsN8pGk.png",
            "https://i.imgur.com/gPvmwHb.png",
            "https://i.imgur.com/LFZHd2p.png"
        ],
        link: "https://mentup.ru/?utm_source=menshikov.agency",
        duration: "13 дней",
        layout: false,
    },
    {
        id: 12123,
        title: 'Дизайн сайта News.Mentup.Ru',
        description: "Актуальные новости киберспорта, турниров, аналитика игр и события игровой индустрии",
        category: "design",
        images: [
            "https://i.imgur.com/s6pXTdr.png",
            "https://i.imgur.com/w3EgM4Q.png",
            "https://i.imgur.com/T21QPgq.png",
            "https://i.imgur.com/7xiPprs.png",
            "https://i.imgur.com/7hsq5zA.png"
        ],
        link: "https://news.mentup.ru/?utm_source=menshikov.agency",
        duration: "6 дней",
        layout: false,
    },
    {
        id: 8,
        title: 'Telegram Mini App "Егор Настоящий"',
        description: "Мини-приложение для своего блога и продажи инфопродукта",
        category: "telegram",
        images: [
            "https://i.imgur.com/sKLQFhu.png",
            "https://i.imgur.com/rLCaD7e.png",
            "https://i.imgur.com/RYXxnjO.png",
            "https://i.imgur.com/MGnV45t.png",
            "https://i.imgur.com/WuHyMcx.png",
            "https://i.imgur.com/txO3Nvj.png",
            "https://i.imgur.com/HFXlknR.png",
            "https://i.imgur.com/VHqcBfF.png",
        ],
        link: "https://t.me/son_godd_bot/egor",
        duration: "1 день",
        layout: true,
    },
    {
        id: 9,
        title: 'Telegram Mini App "DAIREN. COMMUNITY"',
        description: "Мини-приложение для продажи инфопродукта",
        category: "telegram",
        images: [
            "https://i.imgur.com/uq5N29y.png",
            "https://i.imgur.com/HFOMFN4.png",
            "https://i.imgur.com/5m5mN6m.png",
            "https://i.imgur.com/MCcA8fb.png",
            "https://i.imgur.com/M6bXj9w.png",
            "https://i.imgur.com/AGOguTF.png",
        ],
        link: "https://t.me/dairenmaxxing_bot/dkm",
        duration: "1 день",
        layout: true,
    },
]