export const projects = [
    {
        id: 1,
        title: 'Telegram Mini App "PROPAGANDA AGENCY"',
        description: "Мини-приложение для медиа-агентства",
        category: "telegram",
        images: [
            "https://i.imgur.com/eAxFqoJ.png",
            "https://i.imgur.com/7UBVfn0.png",
            "https://i.imgur.com/KuRfw8f.png",
            "https://i.imgur.com/8MxHvBD.png",
            "https://i.imgur.com/S1fR7wO.png",
            "https://i.imgur.com/nILPThK.png",
            "https://i.imgur.com/pTLU5Yt.png",
            "https://i.imgur.com/VoXe00i.png",
            "https://i.imgur.com/DLiMJFR.png",
            "https://i.imgur.com/tkxy3we.png",
            "https://i.imgur.com/OSeFrEc.png",
            "https://i.imgur.com/u1frdeI.png",
            "https://i.imgur.com/yQhzByv.png",
            "https://i.imgur.com/qC5rUIB.png"
        ],
        link: "https://t.me/propagan_agency_bot/AGENCY",
        duration: "< 1 дня",
        layout: false,
    },
    {
        id: 2,
        title: 'Telegram Mini App "СИСТЕМА: продай на миллион за вечер" ',
        description: "Мини-приложение с интерактивным опросом и продажей инфопродукта",
        category: "telegram",
        images: [
            "https://i.imgur.com/uaQmJlz.png",
            "https://i.imgur.com/j0aXzMp.png",
            "https://i.imgur.com/4h8PW72.png",
            "https://i.imgur.com/O5h6by7.png",
            "https://i.imgur.com/AQewDy9.png",
            "https://i.imgur.com/wbMwrhy.png"
        ],
        link: "https://t.me/SISTEMAzh_bot/system",
        duration: "2 дня",
        layout: false,
    },
    {
        id: 3,
        title: 'Telegram Бот "Ethos Select"',
        description: "Бот для онлайн-магазина: заказы, заявки, админка",
        category: "bot",
        images: [
            "https://i.imgur.com/ATegrE3.png",
            "https://i.imgur.com/zzNQtsN.png",
            "https://i.imgur.com/q4zozwr.png",
            "https://i.imgur.com/hAGSA2x.png",
            "https://i.imgur.com/oUs0m3o.png",
            "https://i.imgur.com/w8NNb8J.png",
            "https://i.imgur.com/tqSRLs2.png"
        ],
        link: "https://t.me/ethos_select_bot",
        duration: "2 дня",
        layout: false,
    },
    {
        id: 4,
        title: 'Сайт "Гимназия ЛИДЕР"',
        description: "Современный сайт для современной школы",
        category: "website",
        images: [
            "https://i.imgur.com/vdwGuUs.png",
            "https://i.imgur.com/vaNlVfH.png",
            "https://i.imgur.com/l7OydoS.png",
            "https://i.imgur.com/d6ruShq.png",
            "https://i.imgur.com/fMsrzmN.png",
            "https://i.imgur.com/a14zmpu.png",
            "https://i.imgur.com/4SNYszl.png",
            "https://i.imgur.com/nFptiX2.png",
        ],
        link: "https://lider-gym.vercel.app/about/gallery",
        duration: "1 день",
        layout: false,
    },
    {
        id: 5,
        title: 'Telegram Mini Apps "Premium Brand"',
        description: "Мини-приложение для онлайн-магазина: дизайн, каталог товаров, интеграция с Google Excel",
        category: "telegram",
        images: [
            "https://i.imgur.com/hc4DQud.png",
            "https://i.imgur.com/gDvI41U.png",
            "https://i.imgur.com/xGCmrOJ.png",
            "https://i.imgur.com/xbKF336.png",
            "https://i.imgur.com/n8vA8KV.png"
        ],
        link: "https://t.me/premiumbrand_shop_bot/app",
        duration: "1 день",
        layout: false,
    },
    {
        id: 6,
        title: 'Telegram Mini Apps "Получить разбор на эфире"',
        description: "Мини-приложение для оставление заявки для разбора на эфире + интеграция с Google Excel",
        category: "telegram",
        images: [
            "https://i.imgur.com/1MhVtCm.png",
            "https://i.imgur.com/fm2o8ds.png",
            "https://i.imgur.com/5S6SsHk.png",
            "https://i.imgur.com/kgZAn92.png",
            "https://i.imgur.com/AncEYaG.png",
            "https://i.imgur.com/L3XagRi.png"
        ],
        link: "https://t.me/tigran_says_bot/app",
        duration: "< 1 день",
        layout: false,
    },
    {
        id: 7,
        title: 'Telegram Mini Apps "Получить разбор на эфире" 2',
        description: "Мини-приложение для оставление заявки для разбора на эфире + интеграция с Google Excel",
        category: "telegram",
        images: [
            "https://i.imgur.com/2YGeUEx.png",
            "https://i.imgur.com/bV62vjO.png",
            "https://i.imgur.com/1c5edn9.png",
            "https://i.imgur.com/nyTQvX0.png",
            "https://i.imgur.com/GPqcLST.png",
            "https://i.imgur.com/yoTOcM3.png"
        ],
        link: "https://t.me/villagi0_bot/bot",
        duration: "< 1 день",
        layout: false,
    },
    {
        id: 8,
        title: 'Telegram Mini Apps "Егор Настоящий"',
        description: "Мини-приложение для своего блога и продажи инфопродукта",
        category: "telegram",
        images: [
            "https://i.imgur.com/sKLQFhu.png",
            "https://i.imgur.com/rLCaD7e.png",
            "https://i.imgur.com/RYXxnjO.png",
            "https://i.imgur.com/MGnV45t.png",
            "https://i.imgur.com/WuHyMcx.png",
            "https://i.imgur.com/txO3Nvj.png",
            "https://i.imgur.com/HFXlknR.png",
            "https://i.imgur.com/VHqcBfF.png",
        ],
        link: "https://t.me/son_godd_bot/egor",
        duration: "1 день",
        layout: true,
    },
    {
        id: 9,
        title: 'Telegram Mini Apps "DAIREN. COMMUNITY"',
        description: "Мини-приложение для продажи инфопродукта",
        category: "telegram",
        images: [
            "https://i.imgur.com/uq5N29y.png",
            "https://i.imgur.com/HFOMFN4.png",
            "https://i.imgur.com/5m5mN6m.png",
            "https://i.imgur.com/MCcA8fb.png",
            "https://i.imgur.com/M6bXj9w.png",
            "https://i.imgur.com/AGOguTF.png",
        ],
        link: "https://t.me/dairenmaxxing_bot/dkm",
        duration: "1 день",
        layout: true,
    },
]